baseurl = "http://localhost:1313/"
title = "RonanBlog"
languageCode = "zh-CN"
paginate = "6" # 每页帖子数
theme = "mainroad"

[Params]
    author = "Ronan"
    description = "向前每多走一步，热爱和勇气就会多一分" # Description of your site
    avatar = "img/avatar.png" # 作者图标
    opengraph = true
    readmore = false # 如果为 true，则在列表中显示“阅读更多”按钮
    authorbox = true # 如果为 true，则在页面底部显示作者框
    pager = true
    post_meta = ["date", "categories"] # 帖子元信息的顺序
    mainSections = ["post", "docs"]

[Params.logo]
    subtitle = "向前每多走一步，热爱和勇气就会多一分" # 首页网站副标题

[Params.sidebar]
    home = "right"   # 配置主页布局
    list = "right"   # 配置列表页面的布局
    single = "right" # 配置单页布局
    #按给定顺序启用小部件
    widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
    recent_num = 5 # 设置“最近文章”小部件中的文章数量
    tags_counter = false # 为“标签”小部件中的每个标签启用计数器（默认情况下禁用）
